package com.example.readerapp.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object NeutralColors {
    val primaryLight = Color(0xFF000000)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF1C1B1B)
    val onPrimaryContainerLight = Color(0xFF858383)
    val secondaryLight = Color(0xFF5D5F5F)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFFAFAFA)
    val onSecondaryContainerLight = Color(0xFF717373)
    val tertiaryLight = Color(0xFFBC0020)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFE8112D)
    val onTertiaryContainerLight = Color(0xFFFFFCFF)
    val errorLight = Color(0xFF8B0016)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFB50D23)
    val onErrorContainerLight = Color(0xFFFFC3C0)
    val backgroundLight = Color(0xFFFDF8F8)
    val onBackgroundLight = Color(0xFF1C1B1B)
    val surfaceLight = Color(0xFFFCF8F8)
    val onSurfaceLight = Color(0xFF1C1B1B)
    val surfaceVariantLight = Color(0xFFE0E3E3)
    val onSurfaceVariantLight = Color(0xFF444748)
    val outlineLight = Color(0xFF747878)
    val outlineVariantLight = Color(0xFFC4C7C7)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF313030)
    val inverseOnSurfaceLight = Color(0xFFF4F0EF)
    val inversePrimaryLight = Color(0xFFC8C6C5)
    val surfaceDimLight = Color(0xFFDDD9D9)
    val surfaceBrightLight = Color(0xFFFCF8F8)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF7F3F2)
    val surfaceContainerLight = Color(0xFFF1EDEC)
    val surfaceContainerHighLight = Color(0xFFEBE7E7)
    val surfaceContainerHighestLight = Color(0xFFE5E2E1)

    val primaryLightMediumContrast = Color(0xFF000000)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF1C1B1B)
    val onPrimaryContainerLightMediumContrast = Color(0xFFA8A6A6)
    val secondaryLightMediumContrast = Color(0xFF343637)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF6C6D6D)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF73000F)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFFDB0027)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF730010)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFB50D23)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFFDF8F8)
    val onBackgroundLightMediumContrast = Color(0xFF1C1B1B)
    val surfaceLightMediumContrast = Color(0xFFFCF8F8)
    val onSurfaceLightMediumContrast = Color(0xFF111111)
    val surfaceVariantLightMediumContrast = Color(0xFFE0E3E3)
    val onSurfaceVariantLightMediumContrast = Color(0xFF333737)
    val outlineLightMediumContrast = Color(0xFF4F5354)
    val outlineVariantLightMediumContrast = Color(0xFF6A6E6E)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF313030)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFF4F0EF)
    val inversePrimaryLightMediumContrast = Color(0xFFC8C6C5)
    val surfaceDimLightMediumContrast = Color(0xFFC9C6C5)
    val surfaceBrightLightMediumContrast = Color(0xFFFCF8F8)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFF7F3F2)
    val surfaceContainerLightMediumContrast = Color(0xFFEBE7E7)
    val surfaceContainerHighLightMediumContrast = Color(0xFFDFDCDB)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFD4D1D0)

    val primaryLightHighContrast = Color(0xFF000000)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF1C1B1B)
    val onPrimaryContainerLightHighContrast = Color(0xFFD2D0CF)
    val secondaryLightHighContrast = Color(0xFF2A2C2D)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF48494A)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF60000B)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF970017)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF60000C)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF970019)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFFDF8F8)
    val onBackgroundLightHighContrast = Color(0xFF1C1B1B)
    val surfaceLightHighContrast = Color(0xFFFCF8F8)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFE0E3E3)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF292D2D)
    val outlineVariantLightHighContrast = Color(0xFF464A4A)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF313030)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFC8C6C5)
    val surfaceDimLightHighContrast = Color(0xFFBBB8B7)
    val surfaceBrightLightHighContrast = Color(0xFFFCF8F8)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF4F0EF)
    val surfaceContainerLightHighContrast = Color(0xFFE5E2E1)
    val surfaceContainerHighLightHighContrast = Color(0xFFD7D4D3)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC9C6C5)

    val primaryDark = Color(0xFFC8C6C5)
    val onPrimaryDark = Color(0xFF313030)
    val primaryContainerDark = Color(0xFF0F0F0F)
    val onPrimaryContainerDark = Color(0xFF7D7B7B)
    val secondaryDark = Color(0xFFFFFFFF)
    val onSecondaryDark = Color(0xFF2F3131)
    val secondaryContainerDark = Color(0xFFE2E2E2)
    val onSecondaryContainerDark = Color(0xFF636565)
    val tertiaryDark = Color(0xFFFFB3AF)
    val onTertiaryDark = Color(0xFF68000D)
    val tertiaryContainerDark = Color(0xFFE8112D)
    val onTertiaryContainerDark = Color(0xFFFFFCFF)
    val errorDark = Color(0xFFFFB3AF)
    val onErrorDark = Color(0xFF68000E)
    val errorContainerDark = Color(0xFFB50D23)
    val onErrorContainerDark = Color(0xFFFFC3C0)
    val backgroundDark = Color(0xFF141313)
    val onBackgroundDark = Color(0xFFE5E2E1)
    val surfaceDark = Color(0xFF141313)
    val onSurfaceDark = Color(0xFFE5E2E1)
    val surfaceVariantDark = Color(0xFF444748)
    val onSurfaceVariantDark = Color(0xFFC4C7C7)
    val outlineDark = Color(0xFF8E9192)
    val outlineVariantDark = Color(0xFF444748)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE5E2E1)
    val inverseOnSurfaceDark = Color(0xFF313030)
    val inversePrimaryDark = Color(0xFF5F5E5E)
    val surfaceDimDark = Color(0xFF141313)
    val surfaceBrightDark = Color(0xFF3A3939)
    val surfaceContainerLowestDark = Color(0xFF0E0E0E)
    val surfaceContainerLowDark = Color(0xFF1C1B1B)
    val surfaceContainerDark = Color(0xFF201F1F)
    val surfaceContainerHighDark = Color(0xFF2A2A2A)
    val surfaceContainerHighestDark = Color(0xFF353434)

    val primaryDarkMediumContrast = Color(0xFFDFDCDB)
    val onPrimaryDarkMediumContrast = Color(0xFF262525)
    val primaryContainerDarkMediumContrast = Color(0xFF929090)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFFFFFFF)
    val onSecondaryDarkMediumContrast = Color(0xFF2F3131)
    val secondaryContainerDarkMediumContrast = Color(0xFFE2E2E2)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF464849)
    val tertiaryDarkMediumContrast = Color(0xFFFFD2CE)
    val onTertiaryDarkMediumContrast = Color(0xFF540008)
    val tertiaryContainerDarkMediumContrast = Color(0xFFFF5354)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFD2CF)
    val onErrorDarkMediumContrast = Color(0xFF540009)
    val errorContainerDarkMediumContrast = Color(0xFFFF5356)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF141313)
    val onBackgroundDarkMediumContrast = Color(0xFFE5E2E1)
    val surfaceDarkMediumContrast = Color(0xFF141313)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF444748)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFDADDDD)
    val outlineDarkMediumContrast = Color(0xFFAFB2B3)
    val outlineVariantDarkMediumContrast = Color(0xFF8D9191)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFE5E2E1)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A2A)
    val inversePrimaryDarkMediumContrast = Color(0xFF484848)
    val surfaceDimDarkMediumContrast = Color(0xFF141313)
    val surfaceBrightDarkMediumContrast = Color(0xFF454444)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF070707)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF1E1D1D)
    val surfaceContainerDarkMediumContrast = Color(0xFF282828)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF333232)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3D3D)

    val primaryDarkHighContrast = Color(0xFFF3EFEF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFC5C2C1)
    val onPrimaryContainerDarkHighContrast = Color(0xFF0B0B0B)
    val secondaryDarkHighContrast = Color(0xFFFFFFFF)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFE2E2E2)
    val onSecondaryContainerDarkHighContrast = Color(0xFF282A2B)
    val tertiaryDarkHighContrast = Color(0xFFFFECEA)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFFFAEA9)
    val onTertiaryContainerDarkHighContrast = Color(0xFF220001)
    val errorDarkHighContrast = Color(0xFFFFECEA)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA9)
    val onErrorContainerDarkHighContrast = Color(0xFF220002)
    val backgroundDarkHighContrast = Color(0xFF141313)
    val onBackgroundDarkHighContrast = Color(0xFFE5E2E1)
    val surfaceDarkHighContrast = Color(0xFF141313)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF444748)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFEEF0F1)
    val outlineVariantDarkHighContrast = Color(0xFFC0C3C4)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE5E2E1)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF484848)
    val surfaceDimDarkHighContrast = Color(0xFF141313)
    val surfaceBrightDarkHighContrast = Color(0xFF51504F)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF201F1F)
    val surfaceContainerDarkHighContrast = Color(0xFF313030)
    val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B3B)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF484646)

}

val neutralLightScheme = lightColorScheme(
    primary = NeutralColors.primaryLight,
    onPrimary = NeutralColors.onPrimaryLight,
    primaryContainer = NeutralColors.primaryContainerLight,
    onPrimaryContainer = NeutralColors.onPrimaryContainerLight,
    secondary = NeutralColors.secondaryLight,
    onSecondary = NeutralColors.onSecondaryLight,
    secondaryContainer = NeutralColors.secondaryContainerLight,
    onSecondaryContainer = NeutralColors.onSecondaryContainerLight,
    tertiary = NeutralColors.tertiaryLight,
    onTertiary = NeutralColors.onTertiaryLight,
    tertiaryContainer = NeutralColors.tertiaryContainerLight,
    onTertiaryContainer = NeutralColors.onTertiaryContainerLight,
    error = NeutralColors.errorLight,
    onError = NeutralColors.onErrorLight,
    errorContainer = NeutralColors.errorContainerLight,
    onErrorContainer = NeutralColors.onErrorContainerLight,
    background = NeutralColors.backgroundLight,
    onBackground = NeutralColors.onBackgroundLight,
    surface = NeutralColors.surfaceLight,
    onSurface = NeutralColors.onSurfaceLight,
    surfaceVariant = NeutralColors.surfaceVariantLight,
    onSurfaceVariant = NeutralColors.onSurfaceVariantLight,
    outline = NeutralColors.outlineLight,
    outlineVariant = NeutralColors.outlineVariantLight,
    scrim = NeutralColors.scrimLight,
    inverseSurface = NeutralColors.inverseSurfaceLight,
    inverseOnSurface = NeutralColors.inverseOnSurfaceLight,
    inversePrimary = NeutralColors.inversePrimaryLight,
    surfaceDim = NeutralColors.surfaceDimLight,
    surfaceBright = NeutralColors.surfaceBrightLight,
    surfaceContainerLowest = NeutralColors.surfaceContainerLowestLight,
    surfaceContainerLow = NeutralColors.surfaceContainerLowLight,
    surfaceContainer = NeutralColors.surfaceContainerLight,
    surfaceContainerHigh = NeutralColors.surfaceContainerHighLight,
    surfaceContainerHighest = NeutralColors.surfaceContainerHighestLight,
)

val neutralDarkScheme = darkColorScheme(
    primary = NeutralColors.primaryDark,
    onPrimary = NeutralColors.onPrimaryDark,
    primaryContainer = NeutralColors.primaryContainerDark,
    onPrimaryContainer = NeutralColors.onPrimaryContainerDark,
    secondary = NeutralColors.secondaryDark,
    onSecondary = NeutralColors.onSecondaryDark,
    secondaryContainer = NeutralColors.secondaryContainerDark,
    onSecondaryContainer = NeutralColors.onSecondaryContainerDark,
    tertiary = NeutralColors.tertiaryDark,
    onTertiary = NeutralColors.onTertiaryDark,
    tertiaryContainer = NeutralColors.tertiaryContainerDark,
    onTertiaryContainer = NeutralColors.onTertiaryContainerDark,
    error = NeutralColors.errorDark,
    onError = NeutralColors.onErrorDark,
    errorContainer = NeutralColors.errorContainerDark,
    onErrorContainer = NeutralColors.onErrorContainerDark,
    background = NeutralColors.backgroundDark,
    onBackground = NeutralColors.onBackgroundDark,
    surface = NeutralColors.surfaceDark,
    onSurface = NeutralColors.onSurfaceDark,
    surfaceVariant = NeutralColors.surfaceVariantDark,
    onSurfaceVariant = NeutralColors.onSurfaceVariantDark,
    outline = NeutralColors.outlineDark,
    outlineVariant = NeutralColors.outlineVariantDark,
    scrim = NeutralColors.scrimDark,
    inverseSurface = NeutralColors.inverseSurfaceDark,
    inverseOnSurface = NeutralColors.inverseOnSurfaceDark,
    inversePrimary = NeutralColors.inversePrimaryDark,
    surfaceDim = NeutralColors.surfaceDimDark,
    surfaceBright = NeutralColors.surfaceBrightDark,
    surfaceContainerLowest = NeutralColors.surfaceContainerLowestDark,
    surfaceContainerLow = NeutralColors.surfaceContainerLowDark,
    surfaceContainer = NeutralColors.surfaceContainerDark,
    surfaceContainerHigh = NeutralColors.surfaceContainerHighDark,
    surfaceContainerHighest = NeutralColors.surfaceContainerHighestDark,
)
